### ISSUE TITLE
Replace Chatter's default layouts in SQL import with template is="starcounter-composition"

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Chatter#18]
This task is the part of the effort to implement https://starcounter.gitbooks.io/rebelslounge/content/app/client/layouts/longterm_solution_md.html

Use Products app as reference for this task (https://github.com/StarcounterSamples/Products/issues/18)

---

Currently, Chatter contains default layout information that comes as an SQL import (https://github.com/StarcounterSamples/Chatter/blob/master/Content/default-layout.sql). 

Remove that SQL file and the helper class that uses it. Provide equivalent information in form of `template is="declarative-shadow-dom"` (aka `template is="starcounter-composition"`)..

Do this on Chatter `develop` branch (see [branching policy](https://starcounter.gitbooks.io/guidelines/content/branching.html))

**Comment by warpech** [comment]
@diliger any progress on this?

**Comment by warpech** [comment]
Probably it makes sense to do it on one PR with #12.

**Comment by warpech** [comment]
Guidelines are here: https://docs.starcounter.io/guides/web-apps/html-view-guidelines/

**Comment by diliger** [comment]
Sorry, i definitely can't understand how it works.
I'v installed SC 2.2 but still don't see any usage of SQL layouts, if I change them or remove directly in database nothing changes in the output.

What am I doing wrong?

**Comment by warpech** [comment]
I will do it by reading the JSON organoleptically and assign you to review.

**Comment by warpech** [comment]
I have created a PR that just removes the SQL layouts. I don't think there was actually any custom layouts in this file. 

The default HTML rendering looks good, it just should be moved to `<template is="declarative-shadow-dom">` as much as possible. @diliger could you do that, based on how People app does it and https://docs.starcounter.io/guides/web-apps/html-view-guidelines/ ?

**Comment by diliger** [comment]
here is a first commit for two pages, is that correct?
[commit](https://github.com/StarcounterApps/Chatter/commit/390a594980a246c39f2f5251181ff1739879fa9d)

**Comment by warpech** [comment]
Added some comments in https://github.com/StarcounterApps/Chatter/commit/390a594980a246c39f2f5251181ff1739879fa9d. Please start a PR, it will be easier to review

**Comment by warpech** [comment]
Done in https://github.com/StarcounterApps/Chatter/pull/27
