### ISSUE TITLE
Remove dom-bind-notifier, no longer needed

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Chatter#23]
`dom-bind-notifier` produces warnings in Starcounter 2.2+ saying that it is no longer needed

**Comment by diliger** [comment]
Where is it? 
I try to find it with search but nothing was found.

**Comment by warpech** [comment]
At least in this one file: https://github.com/StarcounterApps/Chatter/blob/develop/wwwroot/Chatter/ViewModels/ChooseAttachmentPage.html

Is that file used at all?

**Comment by diliger** [comment]
No, it is excluded from the project, that's why i couldn't find it.

**Comment by warpech** [comment]
Great! Then three `ChooseAttachmentPage` files (json, json.cs, html) can be removed from the repo to fix this issue

**Comment by diliger** [comment]
PR #28

**Comment by diliger** [comment]
Merged. Closed.
