### ISSUE TITLE
Apply the new pattern to create MasterPage

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Chatter#38]
A new pattern to create MasterPage was discussed in https://github.com/Starcounter/Guidelines/issues/23 and implemented for reference in https://github.com/StarcounterApps/Website/pull/106.

Please apply the same pattern in Chatter app, namely:

- rename the class `StandalonePage` to `MasterPage` (json, json.cs, html files)
- replace `Handle.GET("/chatter/standalone"` handler with a `GetSessionFromMaster` method

**Comment by warpech** [comment]
Suggested reviewer: @warpech

**Comment by Mackiovello** [comment]
Fixed in #39, closing
