### ISSUE TITLE
Consider branch / fork with paper version

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Chatter#8]
There is already made UI with Material Design https://github.com/pubnub/paper-chat maybe we can integrate it with Starcounter app?

**Comment by warpech** [comment]
If we were to change the UI for something cooler, I think this would be a nice design: http://tympanus.net/Development/CreativeGooeyEffects/

**Comment by warpech** [comment]
We will not be doing this. It was decided that Chatter will be transformed into a more generic "events timeline" app, where chat messages are just one kind of events on the timeline.

cc @andwah, @Loudness
